version: '3'

services:

  db:
    image: postgres

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_BUILD_ID: ${CI_BUILD_ID}
        CI_BUILD_REF: ${CI_BUILD_REF}
        CI_BUILD_TIME: ${CI_BUILD_TIME}
        CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
        RAILS_ENV: production
    image: ${DOCKER_IMAGE_PROD:-acme101/ror-hello-world:develop}
    depends_on:
      - db
    environment:
      PORT: 3000
      VIRTUAL_HOST: ror.teracy.dev, ~^ror\..*\.xip\.io
      HTTPS_METHOD: noredirect # support both http and https
    env_file:
      - .env-common
      - .env-dev
    ports:
      - 3000
    network_mode: bridge