version: '3'

services:

  ngrok-review:
    image: ${NGROK_REVIEW_IMAGE:-wernight/ngrok}
    command: ngrok http -host-header=review.ror.acme.dev nginx-proxy:80
    environment:
      - VIRTUAL_HOST=ngrok-review.ror.acme.dev
      - HTTPS_METHOD=noredirect
    ports:
      - 4040
    depends_on:
      - app-review
    external_links:
      - nginx-proxy
    network_mode: bridge

  app-review:
    image: ${APP_REVIEW_IMAGE}
    environment:
      PORT: 8080
      VIRTUAL_HOST: ${APP_REVIEW_VIRTUAL_HOST:-review.ror.acme.dev, ~^review\.ror\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    env_file:
      - .env-common
      - .env-review
    depends_on:
      - db-review
    links:
      - db-review:db
    restart: unless-stopped
    network_mode: bridge

  db-review:
    image: ${DB_DEV_IMAGE:-postgres:9.6.3-alpine}
    restart: unless-stopped
    network_mode: bridge
