default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_PRODUCTION'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  url: <%= ENV['DATABASE_URI'] %>