apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.service.internalPort | quote }}
          # for rolling updates without downtime
          # see: https://github.com/kubernetes/kubernetes/issues/33664#issuecomment-292895327
          - name: LAST_DEPLOYED
            value: {{ .Values.image.lastDeployed | quote }}
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: secret-key-base
          - name: DATABASE_HOST_PRODUCTION
            value: {{ .Values.app.databaseHostProduction }}
          - name: DATABASE_PRODUCTION
            value: {{ .Values.app.databaseProduction }}
          - name: DATABASE_USER_PRODUCTION
            value: {{ .Values.app.databaseUserProduction }}
          - name: DATABASE_PORT_PRODUCTION
            value: {{ .Values.app.databasePortProduction }}
          - name: DATABASE_PASSWORD_PRODUCTION
            value: {{ .Values.app.databasePasswordProduction }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: registry.gitlab.com
